fixing pathway of Transaction Fees
superseed-xyz/docs pull request #46
Opened 2024-07-18 18:40 UTC by Budalebah

correction of pathway https://docs.optimism.io/stack/transactions/fees

2024-07-22 11:38 UTC, 0xNikolas requested changes

2024-07-22 11:38 UTC, 0xNikolas commented on pages/tokens.mdx
> +[Token Request Form](https://superseedxyz.typeform.com/to/c2J8j8m7)
What is the reason for removing the card?

2024-07-22 11:44 UTC, 0xNikolas requested changes

2024-07-22 11:44 UTC, 0xNikolas commented on pages/tokens.mdx
> +ℹ️ **Guidelines**
Any reason you removed the Callout?

2024-07-23 08:58 UTC, closed without merging

2024-07-23 09:00 UTC, 0xNikolas commented
Please create a pull request with only this changed file `pages/build-on-superseed/differences-compared-to-ethereum.mdx`

2024-07-23 11:27 UTC, Budalebah commented
https://github.com/superseed-xyz/docs/pull/50/commits/a6fdf371519724ddc40ee5ff719b14f3f2041037 done